/* Run the production interaction handlers without a browser or personal save. */
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(process.env.CARAVAN_UI_SOURCE||'src/07-ui.js','utf8');
function load(ctx,name){const start=source.indexOf('  function '+name+'(');assert(start>=0,name);const end=source.indexOf('\n  function ',start+4);vm.runInContext(source.slice(start,end),ctx);return ctx[name];}
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
class Node{
 constructor(kind='div'){this.kind=kind;this.children=[];this.dataset={};this.attributes={};this.style={setProperty:()=>{}};this.classes=new Set();this.classList={contains:c=>this.classes.has(c),toggle:(c,on)=>{on??=!this.classes.has(c);on?this.classes.add(c):this.classes.delete(c);return on;}};}
 set className(value){this.classes=new Set(value.split(' '));}get className(){return [...this.classes].join(' ');}
 setAttribute(k,v){this.attributes[k]=v;}removeAttribute(k){delete this.attributes[k];}
 appendChild(n){n.parentElement=this;this.children.push(n);}insertBefore(n,b){n.parentElement=this;this.children.splice(this.children.indexOf(b),0,n);}
 remove(){this.parentElement.children=this.parentElement.children.filter(n=>n!==this);}
 focus(){this.focused=true;}
 setPointerCapture(id){this.capturedPointer=id;}
 querySelector(s){return this.children.find(n=>s==='button.scene-zoom'?n.kind==='button'&&n.classes.has('scene-zoom'):s==='[data-story-scene-next]'?'storySceneNext'in n.dataset:n.classes.has(s.slice(1)))||null;}
}
function fixture(){
 const frame=new Node(),img=new Node('img'),oldZoom=new Node('span');img.className='event-scene';img.complete=true;img.naturalWidth=1280;img.naturalHeight=720;oldZoom.className='scene-zoom';frame.appendChild(img);frame.appendChild(oldZoom);
 const sheet={classList:{contains:()=>true},querySelector:s=>s==='.event-scene-frame'?frame:null};
 const state={index:0,turns:[1,2,3],readerMode:'current'};
 const reader={scrollHeight:100,scrollTop:0,clientHeight:100,closest:()=>sheet,scrollBy:({top})=>{reader.scrollTop=Math.min(reader.scrollHeight-reader.clientHeight,reader.scrollTop+top);}};
 let rendered=0,auto=0;
 const ctx=vm.createContext({curStory:state,Element:Node,setTimeout:()=>0,document:{createElement:t=>new Node(t)},heldStoryAdvanceKeys:new Set(),clearStoryAuto:()=>{},scheduleStoryAuto:()=>auto++,renderStoryState:()=>rendered++,requestAnimationFrame:fn=>fn(),alignStoryLatest:()=>{},$:s=>s==='#ev-sheet .story-reader'?reader:sheet});
 load(ctx,'advanceStory');load(ctx,'wireSceneZoom')(sheet);
 return {ctx,sheet,state,frame,reader,next:frame.querySelector('[data-story-scene-next]'),zoom:frame.querySelector('button.scene-zoom'),rendered:()=>rendered};
}
const event=(props={})=>({preventDefault(){this.prevented=true;},stopPropagation(){this.stopped=true;},...props});
test('scene click advances one current speech and never enters zoom',()=>{const f=fixture();f.next.onclick(event());assert.equal(f.state.index,1);assert.equal(f.rendered(),1);assert(!f.frame.classList.contains('zoomed'));});
test('holding the scene pauses automatic reading until pointer release or cancellation',()=>{const f=fixture();f.next.onpointerdown(event({clientX:90,clientY:70}));assert.equal(f.state.userHoldingStory,true);f.next.onpointerup(event({clientX:91,clientY:71}));assert.equal(f.state.userHoldingStory,false);f.next.onpointerdown(event({clientX:90,clientY:70}));f.next.onpointercancel();assert.equal(f.state.userHoldingStory,false);});
test('scene retains pointer ownership outside its bounds and releases on lost capture',()=>{const f=fixture();f.next.onpointerdown(event({pointerId:7,clientX:90,clientY:70}));assert.equal(f.next.capturedPointer,7);assert.equal(f.state.userHoldingStory,true);f.next.onlostpointercapture();assert.equal(f.state.userHoldingStory,false);f.next.onclick(event());assert.equal(f.state.index,0);});
test('picture swipe/cancel do not consume a speech; the next fresh tap works',()=>{const f=fixture();f.next.onpointerdown(event({clientX:90,clientY:70}));f.next.onpointerup(event({clientX:90,clientY:130}));f.next.onclick(event());assert.equal(f.state.index,0);f.next.onpointerdown(event({clientX:90,clientY:70}));f.next.onpointercancel();f.next.onclick(event());assert.equal(f.state.index,0);f.next.onpointerdown(event({clientX:90,clientY:70}));f.next.onpointerup(event({clientX:91,clientY:71}));f.next.onclick(event());assert.equal(f.state.index,1);});
test('held keyboard input cannot skip into the next decision',()=>{const f=fixture();f.next.onkeydown(event({key:'Enter',code:'Enter',repeat:false}));assert.equal(f.state.index,1);f.next.onkeydown(event({key:'Enter',code:'Enter',repeat:true}));f.next.onkeydown(event({key:'Enter',code:'Enter',repeat:false}));assert.equal(f.state.index,1);f.ctx.heldStoryAdvanceKeys.delete('Enter');f.next.onkeydown(event({key:'Enter',code:'Enter',repeat:false}));assert.equal(f.state.index,2);f.ctx.heldStoryAdvanceKeys.clear();f.next.onclick(event());assert.equal(f.state.index,2);});
test('zoom is an explicit control; closing it does not advance',()=>{const f=fixture();f.zoom.onclick(event());assert(f.frame.classList.contains('zoomed'));assert.equal(f.zoom.attributes['aria-expanded'],'true');assert.equal(f.state.index,0);f.next.onclick(event());assert(!f.frame.classList.contains('zoomed'));assert.equal(f.state.index,0);f.zoom.onclick(event());const key=event({key:'Escape'});f.frame.onkeydown(key);assert(key.stopped);assert(!f.frame.classList.contains('zoomed'));assert(f.zoom.focused);});
test('review, evidence, and detached event controls cannot advance',()=>{const f=fixture();for(const mode of ['review','inspection']){f.state.readerMode=mode;f.ctx.wireSceneZoom(f.sheet);assert(f.next.disabled);f.next.onclick(event());assert.equal(f.state.index,0);}f.state.readerMode='current';f.ctx.wireSceneZoom(f.sheet);f.ctx.curStory={...f.state};f.next.onclick(event());assert.equal(f.state.index,0);});
test('long speech reveals its lower text before advancing or saving a new index',()=>{const f=fixture();f.reader.scrollHeight=480;f.reader.clientHeight=200;f.next.onclick(event());assert.equal(f.state.index,0);assert.equal(f.reader.scrollTop,150);assert.equal(f.rendered(),0);f.next.onclick(event());assert.equal(f.reader.scrollTop,280);assert.equal(f.state.index,0);f.next.onclick(event());assert.equal(f.state.index,1);assert.equal(f.rendered(),1);});
test('body tap and Enter reveal unread text too; a scroll gesture never advances',()=>{const f=fixture();f.reader.scrollHeight=480;f.reader.clientHeight=200;load(f.ctx,'wireStoryReviewPause')(f.state,1);f.reader.onpointerdown(event({clientX:90,clientY:70}));f.reader.onpointerup(event({clientX:91,clientY:71}));assert.equal(f.state.index,0);assert.equal(f.reader.scrollTop,150);f.reader.onkeydown(event({key:'Enter',code:'Enter',repeat:false}));assert.equal(f.reader.scrollTop,280);assert.equal(f.state.index,0);f.reader.onpointerdown(event({clientX:90,clientY:70}));f.reader.onpointerup(event({clientX:90,clientY:120}));assert.equal(f.state.index,0);f.reader.onpointerdown(event({clientX:90,clientY:70}));f.reader.onpointerup(event({clientX:91,clientY:71}));assert.equal(f.state.index,1);});
test('combat retains its existing tap-to-zoom frame and scrolling behavior',()=>{const f=fixture();f.sheet.classList.contains=()=>false;f.ctx.wireSceneZoom(f.sheet);f.frame.onclick();assert(f.frame.classList.contains('zoomed'));f.reader.closest=()=>null;f.reader.scrollHeight=1000;f.ctx.advanceStory(f.state);assert.equal(f.state.index,1);});
test('reading earlier combat transcript by scrolling never advances on tap or Enter',()=>{const f=fixture();f.reader.closest=()=>null;f.reader.scrollHeight=480;f.reader.clientHeight=200;load(f.ctx,'wireStoryReviewPause')(f.state,1);f.reader.onpointerdown(event({clientX:90,clientY:70}));f.reader.onpointerup(event({clientX:91,clientY:71}));f.reader.onkeydown(event({key:'Enter',code:'Enter',repeat:false}));assert.equal(f.state.index,0);assert.equal(f.reader.scrollTop,0);f.reader.scrollTop=280;f.reader.onpointerdown(event({clientX:90,clientY:70}));f.reader.onpointerup(event({clientX:91,clientY:71}));assert.equal(f.state.index,1);});
test('repeated scene setup has one advance control and one zoom control',()=>{const f=fixture();for(let i=0;i<4;i++)f.ctx.wireSceneZoom(f.sheet);assert.equal(f.frame.children.filter(n=>'storySceneNext'in n.dataset).length,1);assert.equal(f.frame.children.filter(n=>n.kind==='button'&&n.classes.has('scene-zoom')).length,1);});
console.log(`${passed} interaction checks passed`);
