/* Exercise zone navigation against the real read-only HOME renderer. */
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const env=vm.createContext({});
vm.runInContext(fs.readFileSync('src/07g-ui-home.js','utf8')+'\nglobalThis.home=HOME;',env);
const HOME=env.home;
const state={party:['minji'],up:{solar:true},keepsakes:{minji:{name:'민지의 접시',desc:'진짜 물건'}},upgrades:[{id:'solar',nm:'태양광',d:'설치한 부품'}]};
const before=JSON.stringify(state);
const node=dataset=>({dataset,hidden:false,onclick:null,attrs:{},setAttribute(k,v){this.attrs[k]=v;},focus(){this.focused=true;},scrollIntoView(){}});
const zones=['shelf','table','bed','roof','rear'].map(id=>node({homeZone:id}));
const panels=zones.map(z=>node({homePanel:z.dataset.homeZone}));
const props=['companion:minji','upgrade:solar'].map(key=>node({homeObject:key}));
const back=node({});
const detail={...node({}),innerHTML:'',querySelector:()=>back};
const container={querySelectorAll:s=>s==='[data-home-object]'?props:s==='[data-home-zone]'?zones:s==='[data-home-panel]'?panels:[],querySelector:()=>detail};
const old=HOME.wire(container,state),cleanup=HOME.wire(container,state);old();
assert.equal(typeof zones[3].onclick,'function','roof must be reachable without scrolling a whole diagram');
props[0].onclick();assert(detail.innerHTML.includes('진짜 물건'));
zones[3].onclick();
assert.equal(zones[3].attrs['aria-pressed'],'true');
assert.equal(panels.filter(p=>!p.hidden).length,1,'only one zone is expanded');
assert.equal(panels.find(p=>!p.hidden).dataset.homePanel,'roof');
assert.equal(detail.hidden,true,'old object detail must not survive a zone change');
assert(props.every(p=>p.attrs['aria-pressed']==='false'));
props[1].onclick();assert.equal(detail.hidden,false);assert(detail.innerHTML.includes('설치한 부품'));
back.onclick();assert(props[1].focused,'return goes to the same physical item');
assert.equal(detail.hidden,true,'return closes the reading panel instead of leaving the room longer');
assert.equal(props[1].attrs['aria-pressed'],'false','closed inspection releases selection');
zones[1].onclick();assert.equal(panels.find(p=>!p.hidden).dataset.homePanel,'table','empty zones also remain inspectable');
assert.equal(JSON.stringify(state),before,'navigation cannot change the save');
cleanup();assert([...zones,...props,back].every(n=>n.onclick===null));
console.log('PASS mobile HOME zone changes, stale detail clearing, same-item return, empty zone, no mutation, cleanup');
