const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const env=vm.createContext({console,setTimeout:()=>0,clearTimeout:()=>{}});
const source=name=>fs.readFileSync('src/'+name,'utf8');
vm.runInContext(source('03-data.js')+'\nglobalThis.data=D;',env);
vm.runInContext(source('03j-camp-conversations.js'),env);
env.S={party:['minji'],day:4,min:1210,campNight:0,comps:{},campMemories:{}};
env.G={recruitApproach:()=>null};
vm.runInContext(source('04e-engine-world.js'),env);
const report={day:4,threat:'비탈에 걸린 우편 수레',objective:'네 사람을 도로로 올린다',keyMoment:'고정 · 밧줄을 묶는다',costs:['피로 +13.9','연료 -2'],newInjuries:[]};
const results={};
for(const code of ['success','partial','failure','retreat']){
 env.S.lastCombatReport={...report,resultCode:code};
 const before=JSON.stringify(env.S),text=env.G.campContext('minji');results[code]=text;
 assert(text.includes('비탈'),'recollection remembers the actual incident');
 assert(!/13\.9|연료 -2|기록에 남은 고비|대가로|목표|고정 ·/.test(text),'recollection is not a mechanics receipt');
 assert(text.length<120&&!text.includes('\n\n'),'one short recollection before the authored conversation');
 assert.equal(JSON.stringify(env.S),before,'reading does not change history');
}
assert.equal(new Set(Object.values(results)).size,4,'success, partial, failure and retreat stay distinct');
assert(results.success.includes('해냈다'));assert(results.partial.includes('끝내지는 못했다'));
assert(results.failure.includes('해내지 못했다'));assert(results.retreat.includes('물러났다'));
env.S.lastCombatReport={...report,resultCode:'unknown'};
assert(!/해냈|죽|다쳤|구했/.test(env.G.campContext('minji')),'unknown outcome never becomes a success or injury');
env.S.lastCombatReport={...report,resultCode:'success',day:1};
env.G.recruitApproach=()=>({label:'고철 3개를 지불한다',memory:'민지와 흩어진 공구를 주웠다.'});
assert.equal(env.G.campContext('minji'),'민지와 흩어진 공구를 주웠다.','old combat and UI choice labels do not intrude');
env.S.campMemories.minji={visits:1};env.S.lastJourneyRecap={from:'yangsan',to:'miryang',day:4};
assert(env.G.campContext('minji').includes('밀양'),'returning visits move on from the recruitment recap');
env.S.lastJourneyRecap=null;assert.equal(env.G.campContext('minji'),'','no fabricated anecdote when nothing is recent');
const legacy='최근 양산에서 밀양까지 온 길을 떠올린다.\n\n「네 사람을 도로로 올린다」 목표를 이루지 못했다. 멈춰야 했던 자리부터 떠올린다. 기록에 남은 고비는 「고정 · 밧줄을 묶는다」였다. 대가로 남은 것은 피로 +13.9였다. 민지는 말을 들으며 달구지 쪽을 한 번 돌아본다.';
env.S.campConversation={id:'camp_0_minji',night:0,cid:'minji',timeLabel:'밤',context:legacy,revisit:false,chapter:1,choiceId:null,chips:[],active:true};
env.S.lastCombatReport={...report,resultCode:'success',day:4};
const frozen=JSON.stringify(env.S.campConversation),event=env.G.campConversationEvent();
assert(!event.turns[0].text.includes('13.9')&&!event.turns[0].text.includes('목표'),'legacy text gets a clean presentation');
assert(event.turns[0].text.includes('해내지 못했다'),'legacy failure never borrows the newer success');
assert.equal(event.readingRecord,legacy,'old saved context stays available as its original record');
assert.equal(JSON.stringify(env.S.campConversation),frozen,'legacy rendering cannot rewrite the saved conversation');
env.S.campConversation.context='그날 실패와 민지의 이야기를 이미 남겼다.';
assert(env.G.campConversationEvent().text.startsWith(env.S.campConversation.context),'authored saved prose stays frozen');
console.log('PASS camp recollections: short, grounded, four outcomes, recent facts, first/revisit, legacy history intact.');
