#!/usr/bin/env python3
"""Build the offline journal font (fonttools + brotli).

Nanum Pen's OFL reserves its original name, so this subset is renamed.
Only the bundled delivery font is embedded; retain the licensed master.
"""
from pathlib import Path
import argparse
import base64
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
FONTS = ROOT / 'assets/fonts'
# The whole journal is handwritten now, including runtime place/item/mission
# names. Collect authored game text, not only the current main-story heading.
SOURCES = sorted(str(path.relative_to(ROOT)) for path in (ROOT / 'src').glob('*.js'))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--bound-draft', action='store_true',
                        help='Generate only the bound-notebook prototype font; leave game assets untouched.')
    draft = parser.parse_args().bound_draft
    sources = ['tools/design-drafts/quest-bound-notebook.html'] if draft else SOURCES
    text = ''.join((ROOT / source).read_text() for source in sources)
    # Do not silently fall back to a machine font for another journal entry.
    chars = set(text) | set('여정 기록 지금 따라갈 단서 다음에 할 일 남겨진 기록 확인한 기록 지나온 단서')
    chars = {ch for ch in chars if 32 <= ord(ch) <= 126 or '\uac00' <= ch <= '\ud7a3' or ch in '·…‘’“”'}
    font = TTFont(FONTS / 'NanumPenScript-Regular.ttf', recalcTimestamp=False)
    options = subset.Options()
    options.flavor = 'woff2'
    options.name_IDs = ['*']
    options.name_languages = ['*']
    sub = subset.Subsetter(options=options)
    sub.populate(text=''.join(sorted(chars)))
    sub.subset(font)
    names = {1: 'Caravan Journal Hand', 2: 'Regular',
             3: 'CaravanJournalHand-Regular-v1', 4: 'Caravan Journal Hand',
             6: 'CaravanJournalHand-Regular', 16: 'Caravan Journal Hand', 17: 'Regular'}
    for record in font['name'].names:
        if record.nameID in names:
            record.string = names[record.nameID].encode(record.getEncoding())
    font.flavor = 'woff2'
    if draft:
        from io import BytesIO
        data = BytesIO()
        font.save(data)
        delivery = data.getvalue()
    else:
        output = FONTS / 'CaravanJournalHand-Regular.woff2'
        font.save(output)
        delivery = output.read_bytes()
    # Sandboxed Studio prototypes have an opaque origin; embed the font to keep
    # the sandbox intact instead of granting same-origin/storage access.
    uri = base64.b64encode(delivery).decode('ascii')
    css = 'quest-bound-font.css' if draft else 'quest-font.css'
    (ROOT / 'tools/design-drafts' / css).write_text(
        '/* Generated by tools/prepare-quest-font.py; OFL: assets/fonts/NanumPenScript-OFL.txt */\n'
        '@font-face{font-family:"Caravan Journal Hand";src:url("data:font/woff2;base64,'
        + uri + '") format("woff2");font-weight:400;font-display:swap}\n')
    print(f'{css}: {len(delivery):,} font bytes / {len(chars)} requested characters')


if __name__ == '__main__':
    main()
