/* ═══════════════════ CINEMATIC SCENES — build.sh가 JPEG를 주입 ═══════════════════ */
D.scenes = {
  'gwangju-market':'__SCENE_GWANGJU_MARKET__',
  'miryang-market':'__SCENE_MIRYANG_MARKET__',
  'miryang-market-hub':'__SCENE_MIRYANG_MARKET_HUB__',
  'daegu-dome':'__SCENE_DAEGU_DOME__',
  'arrival-daegu-dome':'__SCENE_ARRIVAL_DAEGU_DOME__',
  'muju-tunnel':'__SCENE_MUJU_TUNNEL__',
  'jeonju-market':'__SCENE_JEONJU_MARKET__',
  'daejeon-commune':'__SCENE_DAEJEON_COMMUNE__',
  'suwon-fortress':'__SCENE_SUWON_FORTRESS__',
  'seoul-han':'__SCENE_SEOUL_HAN__',
  'arrival-gimhae':'__SCENE_ARRIVAL_GIMHAE__',
  'arrival-yangsan':'__SCENE_ARRIVAL_YANGSAN__',
  'arrival-jinju':'__SCENE_ARRIVAL_JINJU__',
  'arrival-hapcheon':'__SCENE_ARRIVAL_HAPCHEON__',
  'arrival-geochang':'__SCENE_ARRIVAL_GEOCHANG__',
  'arrival-gumi':'__SCENE_ARRIVAL_GUMI__',
  'arrival-gimcheon':'__SCENE_ARRIVAL_GIMCHEON__',
  'arrival-namwon':'__SCENE_ARRIVAL_NAMWON__',
  'arrival-yeongdong':'__SCENE_ARRIVAL_YEONGDONG__',
  'arrival-nonsan':'__SCENE_ARRIVAL_NONSAN__',
  'arrival-gongju':'__SCENE_ARRIVAL_GONGJU__',
  'arrival-cheongju':'__SCENE_ARRIVAL_CHEONGJU__',
  'arrival-cheonan':'__SCENE_ARRIVAL_CHEONAN__',
  'arrival-pyeongtaek':'__SCENE_ARRIVAL_PYEONGTAEK__',
  'arrival-lake':'__SCENE_ARRIVAL_LAKE__',
  'arrival-mall':'__SCENE_ARRIVAL_MALL__',
  'arrival-tower':'__SCENE_ARRIVAL_TOWER__',
  'arrival-spring':'__SCENE_ARRIVAL_SPRING__',
  'arrival-airfield':'__SCENE_ARRIVAL_AIRFIELD__',
  'arrival-solar':'__SCENE_ARRIVAL_SOLAR__',
  'arrival-reststop':'__SCENE_ARRIVAL_RESTSTOP__',
  'arrival-tunnelbook':'__SCENE_ARRIVAL_TUNNELBOOK__',
  'arrival-ulsan':'__SCENE_ARRIVAL_ULSAN__',
  'arrival-yeosu':'__SCENE_ARRIVAL_YEOSU__',
  'arrival-suncheon':'__SCENE_ARRIVAL_SUNCHEON__',
  'arrival-damyang':'__SCENE_ARRIVAL_DAMYANG__',
  'arrival-mokpo':'__SCENE_ARRIVAL_MOKPO__',
  'arrival-andong':'__SCENE_ARRIVAL_ANDONG__',
  'arrival-mungyeong':'__SCENE_ARRIVAL_MUNGYEONG__',
  'arrival-danyang':'__SCENE_ARRIVAL_DANYANG__',
  'arrival-wonju':'__SCENE_ARRIVAL_WONJU__',
  'arrival-daegwallyeong':'__SCENE_ARRIVAL_DAEGWALLYEONG__',
  'arrival-gangneung':'__SCENE_ARRIVAL_GANGNEUNG__',
  'arrival-sokcho':'__SCENE_ARRIVAL_SOKCHO__',
  'arrival-icheon':'__SCENE_ARRIVAL_ICHEON__',
  'arrival-gyeongju':'__SCENE_ARRIVAL_GYEONGJU__',
  'arrival-pohang':'__SCENE_ARRIVAL_POHANG__',
  'arrival-sangju':'__SCENE_ARRIVAL_SANGJU__',
  'arrival-gunsan':'__SCENE_ARRIVAL_GUNSAN__',
  'arrival-chungju':'__SCENE_ARRIVAL_CHUNGJU__',
  'arrival-sejong':'__SCENE_ARRIVAL_SEJONG__',
  'arrival-lighthouse':'__SCENE_ARRIVAL_LIGHTHOUSE__',
  'arrival-drivein':'__SCENE_ARRIVAL_DRIVEIN__',
  'arrival-sunflower':'__SCENE_ARRIVAL_SUNFLOWER__',
  'arrival-maehwa':'__SCENE_ARRIVAL_MAEHWA__',
  'arrival-mingyu-ridge':'__SCENE_ARRIVAL_MINGYU_RIDGE__',
  'arrival-jaeyi-cache':'__SCENE_ARRIVAL_JAEYI_CACHE__',
  'arrival-cablecar':'__SCENE_ARRIVAL_CABLECAR__',
  'arrival-filmset':'__SCENE_ARRIVAL_FILMSET__',
  'kw-defense-line':'__SCENE_KW_DEFENSE_LINE__',
  'perimeter-walker':'__SCENE_PERIMETER_WALKER__',
  'grandfather-garage':'__SCENE_GRANDFATHER_GARAGE__',
  'busan-departure':'__SCENE_BUSAN_DEPARTURE__',
  'story-generation-form':'__SCENE_STORY_GENERATION_FORM__',
  'story-generation-speech':'__SCENE_STORY_GENERATION_SPEECH__',
  'story-generation-theories':'__SCENE_STORY_GENERATION_THEORIES__',
  'story-generation-route':'__SCENE_STORY_GENERATION_ROUTE__',
  'trace-cortis-relic':'__SCENE_TRACE_CORTIS_RELIC__',
  'trace-cortis-beacon':'__SCENE_TRACE_CORTIS_BEACON__',
  'trace-worldcup-chart':'__SCENE_TRACE_WORLDCUP_CHART__',
  'trace-fourcuts':'__SCENE_TRACE_FOURCUTS__',
  'trace-coldbag':'__SCENE_TRACE_COLDBAG__',
  'trace-consent':'__SCENE_TRACE_CONSENT__',
  'seoul-ruins':'__SCENE_SEOUL_RUINS__',
  'seoul-square':'__SCENE_SEOUL_SQUARE__',
  'seoul-base':'__SCENE_SEOUL_BASE__',
  'seoul-core':'__SCENE_SEOUL_CORE__',
  'seoul-testimony':'__SCENE_SEOUL_TESTIMONY__',
  'seoul-decision':'__SCENE_SEOUL_DECISION__',
  'seoul-liberation':'__SCENE_SEOUL_LIBERATION__',
  'seoul-night':'__SCENE_SEOUL_NIGHT__',
  'seoul-uplink-reveal-v1':'__SCENE_SEOUL_UPLINK_REVEAL_V1__',
  'seoul-session-reset-v1':'__SCENE_SEOUL_SESSION_RESET_V1__',
  'generic-discovery':'__SCENE_GENERIC_DISCOVERY__',
  'generic-encounter':'__SCENE_GENERIC_ENCOUNTER__',
  'generic-crisis':'__SCENE_GENERIC_CRISIS__',
  'generic-cheollian':'__SCENE_GENERIC_CHEOLLIAN__',
  'generic-story':'__SCENE_GENERIC_STORY__',
  'event-meet-roadside':'__SCENE_EVENT_MEET_ROADSIDE__',
  'event-meet-family':'__SCENE_EVENT_MEET_FAMILY__',
  'event-meet-trader':'__SCENE_EVENT_MEET_TRADER__',
  'event-meet-craft':'__SCENE_EVENT_MEET_CRAFT__',
  'event-meet-performer':'__SCENE_EVENT_MEET_PERFORMER__',
  'event-meet-pilgrim':'__SCENE_EVENT_MEET_PILGRIM__',
  'event-meet-guard':'__SCENE_EVENT_MEET_GUARD__',
  'event-meet-courier':'__SCENE_EVENT_MEET_COURIER__',
  'event-meet-animal':'__SCENE_EVENT_MEET_ANIMAL__',
  'event-meet-community':'__SCENE_EVENT_MEET_COMMUNITY__',
  'event-find-document':'__SCENE_EVENT_FIND_DOCUMENT__',
  'event-find-signal':'__SCENE_EVENT_FIND_SIGNAL__',
  'event-explore-retail':'__SCENE_EVENT_EXPLORE_RETAIL__',
  'event-explore-civic':'__SCENE_EVENT_EXPLORE_CIVIC__',
  'event-explore-school':'__SCENE_EVENT_EXPLORE_SCHOOL__',
  'event-explore-workshop':'__SCENE_EVENT_EXPLORE_WORKSHOP__',
  'event-explore-farm':'__SCENE_EVENT_EXPLORE_FARM__',
  'event-explore-water':'__SCENE_EVENT_EXPLORE_WATER__',
  'event-explore-transit':'__SCENE_EVENT_EXPLORE_TRANSIT__',
  'event-explore-leisure':'__SCENE_EVENT_EXPLORE_LEISURE__',
  'event-explore-shelter':'__SCENE_EVENT_EXPLORE_SHELTER__',
  'event-ai-drone':'__SCENE_EVENT_AI_DRONE__',
  'event-ai-automation':'__SCENE_EVENT_AI_AUTOMATION__',
  'event-ai-broadcast':'__SCENE_EVENT_AI_BROADCAST__',
  'event-ai-checkpoint':'__SCENE_EVENT_AI_CHECKPOINT__',
  'event-ai-convoy':'__SCENE_EVENT_AI_CONVOY__',
  'event-ai-surveillance':'__SCENE_EVENT_AI_SURVEILLANCE__',
  'event-crisis-engine':'__SCENE_EVENT_CRISIS_ENGINE__',
  'event-crisis-fuel':'__SCENE_EVENT_CRISIS_FUEL__',
  'event-crisis-tire':'__SCENE_EVENT_CRISIS_TIRE__',
  'event-crisis-flood':'__SCENE_EVENT_CRISIS_FLOOD__',
  'event-crisis-weather':'__SCENE_EVENT_CRISIS_WEATHER__',
  'event-crisis-collapse':'__SCENE_EVENT_CRISIS_COLLAPSE__',
  'event-crisis-animal':'__SCENE_EVENT_CRISIS_ANIMAL__',
  'event-crisis-exhaustion':'__SCENE_EVENT_CRISIS_EXHAUSTION_V2__',
  'event-companion-repair':'__SCENE_EVENT_COMPANION_REPAIR__',
  'event-companion-radio':'__SCENE_EVENT_COMPANION_RADIO__',
  'event-companion-meal':'__SCENE_EVENT_COMPANION_MEAL__',
  'event-companion-camp':'__SCENE_EVENT_COMPANION_CAMP__',
  'event-companion-van':'__SCENE_EVENT_COMPANION_VAN__',
  'event-vista-field':'__SCENE_EVENT_VISTA_FIELD__',
  'event-vista-water':'__SCENE_EVENT_VISTA_WATER__',
  'event-vista-mountain':'__SCENE_EVENT_VISTA_MOUNTAIN__',
  'event-vista-road':'__SCENE_EVENT_VISTA_ROAD__',
  'event-vista-town':'__SCENE_EVENT_VISTA_TOWN__',
  'event-vista-night':'__SCENE_EVENT_VISTA_NIGHT__',
  'event-vista-weather':'__SCENE_EVENT_VISTA_WEATHER__',
  'event-vista-remnant':'__SCENE_EVENT_VISTA_REMNANT__',
  'library-bus':'__SCENE_LIBRARY_BUS__',
  'resistance-contact':'__SCENE_RESISTANCE_CONTACT__',
  'sea-captain-contact':'__SCENE_SEA_CAPTAIN_CONTACT__',
  'gangneung-hospital-build':'__SCENE_GANGNEUNG_HOSPITAL_BUILD__',
  'minji-toolbox':'__SCENE_MINJI_TOOLBOX__',
  'parkss-clinic':'__SCENE_PARKSS_CLINIC__',
  'leo-rooftop-song':'__SCENE_LEO_ROOFTOP_SONG__',
  'jaeyi-ledger':'__SCENE_JAEYI_LEDGER__',
  'eunsu-last-shift':'__SCENE_EUNSU_LAST_SHIFT__',
  'postman-letter':'__SCENE_POSTMAN_LETTER__',
  'frequency-tape':'__SCENE_FREQUENCY_TAPE__',
  'grandfather-envelope':'__SCENE_GRANDFATHER_ENVELOPE__',
  'ridge-memorial':'__SCENE_RIDGE_MEMORIAL__',
  'full-house-meal':'__SCENE_FULL_HOUSE_MEAL__',
  'intro-passenger-seat':'__SCENE_INTRO_PASSENGER_SEAT__',
  'intro-cheollian-2026':'__SCENE_INTRO_CHEOLLIAN_2026__',
'intro-ai-chat-era-v1':'assets/scenes/intro-ai-chat-era-v2.webp',
'intro-busan-room-morning-v1':'assets/scenes/intro-busan-room-morning-v1.webp',
'intro-busan-workday-v1':'assets/scenes/intro-busan-workday-v1.webp',
'intro-busan-evening-call-v1':'assets/scenes/intro-busan-evening-call-v1.webp',
  'intro-ai-sovereignty-race-v1':'__SCENE_INTRO_AI_SOVEREIGNTY_RACE_V1__',
  'intro-cheollian-launch-v1':'__SCENE_INTRO_CHEOLLIAN_LAUNCH_V1__',
  'history-transit-trust-v1':'__SCENE_HISTORY_TRANSIT_TRUST_V1__',
  'history-dissent-crackdown-v1':'__SCENE_HISTORY_DISSENT_CRACKDOWN_V1__',
  'history-three-days-silence-v1':'__SCENE_HISTORY_THREE_DAYS_SILENCE_V1__',
  'history-failed-namsan-v1':'__SCENE_HISTORY_FAILED_NAMSAN_V1__',
  'history-parents-resistance-v1':'__SCENE_HISTORY_PARENTS_RESISTANCE_V1__',
  'intro-resistance-begins':'__SCENE_INTRO_RESISTANCE_FIRST_VOICES_V1__',
  'intro-resistance-first-voices-v1':'__SCENE_INTRO_RESISTANCE_FIRST_VOICES_V1__',
  'intro-resistance-underground-v1':'__SCENE_INTRO_RESISTANCE_UNDERGROUND_V1__',
  'memory-busan-terminal-v1':'__SCENE_MEMORY_BUSAN_TERMINAL_V1__',
  'memory-grandfather-workshop-v1':'__SCENE_MEMORY_GRANDFATHER_WORKSHOP_V1__',
  'memory-first-winter-route-v1':'__SCENE_MEMORY_FIRST_WINTER_ROUTE_V1__',
  'memory-empty-workshop-v1':'__SCENE_MEMORY_EMPTY_WORKSHOP_V1__',
  'parents-diversion-checkpoint-v1':'__SCENE_PARENTS_DIVERSION_CHECKPOINT_V1__',
  'parents-father-maintenance-v1':'__SCENE_PARENTS_FATHER_MAINTENANCE_V1__',
  'parents-mother-archive-v1':'__SCENE_PARENTS_MOTHER_ARCHIVE_V1__',
  'parents-failed-namsan-v1':'__SCENE_PARENTS_FAILED_NAMSAN_V1__',
  'parents-mother-reunion-v1':'__SCENE_PARENTS_MOTHER_REUNION_V1__',
  'story-personal-cache-v1':'__SCENE_STORY_PERSONAL_CACHE_V1__',
  'story-system-answer-v1':'__SCENE_STORY_SYSTEM_ANSWER_V1__',
  'resistance-mid-depot-conflict-v1':'__SCENE_RESISTANCE_MID_DEPOT_CONFLICT_V1__',
  'resistance-signal-leak-evacuation-v1':'__SCENE_RESISTANCE_SIGNAL_LEAK_EVACUATION_V1__',
  'resistance-north-route-rehearsal-v1':'__SCENE_RESISTANCE_NORTH_ROUTE_REHEARSAL_V1__',
  'resistance-seoul-edge-choice-v1':'__SCENE_RESISTANCE_SEOUL_EDGE_CHOICE_V1__',
  'resistance-aftermath-v1':'__SCENE_RESISTANCE_AFTERMATH_V1__',
  'resistance-first-contact-v1':'__SCENE_RESISTANCE_FIRST_CONTACT_V1__',
  'resistance-human-check-v1':'__SCENE_RESISTANCE_HUMAN_CHECK_V1__',
  'intro-cheollian-transit-pilot-v1':'__SCENE_INTRO_CHEOLLIAN_TRANSIT_PILOT_V1__',
  'intro-cheollian-transit-rescue-v1':'__SCENE_INTRO_CHEOLLIAN_TRANSIT_RESCUE_V1__',
  'intro-cheollian-field-bots-v1':'__SCENE_INTRO_CHEOLLIAN_FIELD_BOTS_V1__',
  'intro-cheollian-forced-relocation-v1':'__SCENE_INTRO_CHEOLLIAN_FORCED_RELOCATION_V1__',
  'intro-cheollian-human-approval-v1':'__SCENE_INTRO_CHEOLLIAN_HUMAN_APPROVAL_V1__',
  'intro-cheollian-emergency-delegation-v1':'__SCENE_INTRO_CHEOLLIAN_EMERGENCY_DELEGATION_V1__',
  'intro-cheollian-automatic-rule-v1':'__SCENE_INTRO_CHEOLLIAN_AUTOMATIC_RULE_V1__',
  'intro-first-expulsion':'__SCENE_INTRO_FIRST_EXPULSION__',
  'intro-143-years':'__SCENE_INTRO_143_YEARS__',
  'intro-blank-reason':'__SCENE_INTRO_BLANK_REASON__',
  'intro-years-together':'__SCENE_INTRO_YEARS_TOGETHER__',
  'intro-camper-conversion':'__SCENE_INTRO_CAMPER_CONVERSION__',
  'intro-envelope-signal':'__SCENE_INTRO_ENVELOPE_SIGNAL__',
  'intro-departure-choice':'__SCENE_INTRO_DEPARTURE_CHOICE__',
  'intro-parents-discovery':'__SCENE_INTRO_PARENTS_DISCOVERY__',
  'intro-silenced-presentation':'__SCENE_INTRO_SILENCED_PRESENTATION__',
  'intro-family-order-v1':'__SCENE_INTRO_FAMILY_ORDER_V1__',
  'intro-family-farewell-v1':'__SCENE_INTRO_FAMILY_FAREWELL_V1__',
  'intro-current-expulsion':'__SCENE_INTRO_CURRENT_EXPULSION__',
  'intro-dock-aid':'__SCENE_INTRO_DOCK_AID__',
  'intro-appeal-denied':'__SCENE_INTRO_APPEAL_DENIED__',
  'intro-mother-keepsakes':'__SCENE_INTRO_MOTHER_KEEPSAKES__',
  'intro-dashboard-module':'__SCENE_INTRO_DASHBOARD_MODULE__',
  'intro-workshop-departure':'__SCENE_INTRO_WORKSHOP_DEPARTURE__',
  'intro-cold-open-v1':'__SCENE_INTRO_COLD_OPEN_V1__',
  'intro-departure-conversation-v4':'__SCENE_INTRO_DEPARTURE_CONVERSATION_V4__',
  'intro-departure-start-v1':'__SCENE_INTRO_DEPARTURE_START_V1__',
  'onboarding-main-mission-v1':'__SCENE_ONBOARDING_MAIN_MISSION_V1__',
  'onboarding-first-road-scan-v1':'__SCENE_ONBOARDING_FIRST_ROAD_SCAN_V1__',
  'family-verification-key':'__SCENE_FAMILY_VERIFICATION_KEY__',
  'recruit-minji':'__SCENE_RECRUIT_MINJI__',
  'recruit-parkss':'__SCENE_RECRUIT_PARKSS__',
  'recruit-leo':'__SCENE_RECRUIT_LEO__',
  'recruit-jaeyi':'__SCENE_RECRUIT_JAEYI__',
  'recruit-eunsu':'__SCENE_RECRUIT_EUNSU__',
  'recruit-kangwoo':'__SCENE_RECRUIT_KANGWOO__',
  'recruit-minji-meet-action':'__SCENE_RECRUIT_MINJI_MEET_ACTION__',
  'recruit-parkss-meet-action':'__SCENE_RECRUIT_PARKSS_MEET_ACTION__',
  'recruit-leo-meet-action':'__SCENE_RECRUIT_LEO_MEET_ACTION__',
  'recruit-jaeyi-meet-action':'__SCENE_RECRUIT_JAEYI_MEET_ACTION__',
  'recruit-eunsu-meet-action':'__SCENE_RECRUIT_EUNSU_MEET_ACTION__',
  'recruit-kangwoo-meet-action':'__SCENE_RECRUIT_KANGWOO_MEET_ACTION__',
  'recruit-minji-welding':'__SCENE_RECRUIT_MINJI_WELDING__',
  'recruit-parkss-clinic-market-v2':'__SCENE_RECRUIT_PARKSS_CLINIC_MARKET_V2__',
  'recruit-leo-daein-market-v2':'__SCENE_RECRUIT_LEO_DAEIN_MARKET_V2__',
  'recruit-jaeyi-tunnel-exchange-v2':'__SCENE_RECRUIT_JAEYI_TUNNEL_EXCHANGE_V2__',
  'comp-talk-minji-road-v1':'__SCENE_COMP_TALK_MINJI_ROAD_V1__',
  'comp-talk-minji-camp-v1':'__SCENE_COMP_TALK_MINJI_CAMP_V1__',
  'comp-talk-parkss-road-v1':'__SCENE_COMP_TALK_PARKSS_ROAD_V1__',
  'comp-talk-parkss-camp-v1':'__SCENE_COMP_TALK_PARKSS_CAMP_V1__',
  'comp-talk-kangwoo-road-v1':'__SCENE_COMP_TALK_KANGWOO_ROAD_V1__',
  'comp-talk-kangwoo-camp-v1':'__SCENE_COMP_TALK_KANGWOO_CAMP_V1__',
  'comp-talk-leo-road-v1':'__SCENE_COMP_TALK_LEO_ROAD_V1__',
  'comp-talk-leo-camp-v1':'__SCENE_COMP_TALK_LEO_CAMP_V1__',
  'comp-talk-jaeyi-road-v1':'__SCENE_COMP_TALK_JAEYI_ROAD_V1__',
  'comp-talk-jaeyi-camp-v1':'__SCENE_COMP_TALK_JAEYI_CAMP_V1__',
  'comp-talk-eunsu-road-v1':'__SCENE_COMP_TALK_EUNSU_ROAD_V1__',
  'comp-talk-eunsu-camp-v1':'__SCENE_COMP_TALK_EUNSU_CAMP_V1__',
  'camp-home-stage-v1':'__SCENE_CAMP_HOME_STAGE_V1__',
  'recruit-parkss-bus-overturned':'__SCENE_RECRUIT_PARKSS_BUS_OVERTURNED__',
  'recruit-leo-hitch-gesture':'__SCENE_RECRUIT_LEO_HITCH_GESTURE__',
  'recruit-jaeyi-suspension-check':'__SCENE_RECRUIT_JAEYI_SUSPENSION_CHECK__',
  'recruit-eunsu-rooftop':'__SCENE_RECRUIT_EUNSU_ROOFTOP__',
  'recruit-eunsu-sky-point':'__SCENE_RECRUIT_EUNSU_SKY_POINT__',
  'recruit-kangwoo-pickpocket':'__SCENE_RECRUIT_KANGWOO_PICKPOCKET__',
  'recruit-minji-task':'__SCENE_RECRUIT_MINJI_TASK__',
  'recruit-parkss-task':'__SCENE_RECRUIT_PARKSS_TASK__',
  'recruit-leo-task':'__SCENE_RECRUIT_LEO_TASK__',
  'recruit-jaeyi-task':'__SCENE_RECRUIT_JAEYI_TASK__',
  'recruit-eunsu-task':'__SCENE_RECRUIT_EUNSU_TASK__',
  'recruit-kangwoo-task':'__SCENE_RECRUIT_KANGWOO_TASK__',
  'recruit-minji-follow':'__SCENE_RECRUIT_MINJI_FOLLOW__',
  'recruit-minji-join':'__SCENE_RECRUIT_MINJI_JOIN__',
  'recruit-parkss-follow':'__SCENE_RECRUIT_PARKSS_FOLLOW__',
  'recruit-parkss-join':'__SCENE_RECRUIT_PARKSS_JOIN__',
  'recruit-leo-follow':'__SCENE_RECRUIT_LEO_FOLLOW__',
  'recruit-leo-join':'__SCENE_RECRUIT_LEO_JOIN__',
  'recruit-jaeyi-follow':'__SCENE_RECRUIT_JAEYI_FOLLOW__',
  'recruit-jaeyi-join':'__SCENE_RECRUIT_JAEYI_JOIN__',
  'recruit-eunsu-follow':'__SCENE_RECRUIT_EUNSU_FOLLOW__',
  'recruit-eunsu-join':'__SCENE_RECRUIT_EUNSU_JOIN__',
  'recruit-kangwoo-follow':'__SCENE_RECRUIT_KANGWOO_FOLLOW__',
  'recruit-kangwoo-join':'__SCENE_RECRUIT_KANGWOO_JOIN__',
  'recruit-minji-join-decision':'__SCENE_RECRUIT_MINJI_JOIN_DECISION__',
  'recruit-parkss-join-decision':'__SCENE_RECRUIT_PARKSS_JOIN_DECISION__',
  'recruit-leo-join-decision':'__SCENE_RECRUIT_LEO_JOIN_DECISION__',
  'recruit-jaeyi-join-decision':'__SCENE_RECRUIT_JAEYI_JOIN_DECISION__',
  'recruit-eunsu-join-decision':'__SCENE_RECRUIT_EUNSU_JOIN_DECISION__',
  'recruit-kangwoo-join-decision':'__SCENE_RECRUIT_KANGWOO_JOIN_DECISION__',
  'combat-perimeter-warning':'__SCENE_COMBAT_PERIMETER_WARNING__',
  'combat-walker-disable':'__SCENE_COMBAT_WALKER_DISABLE__',
  'combat-drone-swarm':'__SCENE_COMBAT_DRONE_SWARM__',
  'combat-checkpoint-breach':'__SCENE_COMBAT_CHECKPOINT_BREACH__',
  'roadcrew-line':'__SCENE_ROADCREW_LINE__',
  'roadcrew-bridge':'__SCENE_ROADCREW_BRIDGE__',
  'roadcrew-washout':'__SCENE_ROADCREW_WASHOUT__',
  'roadcrew-sign':'__SCENE_ROADCREW_SIGN__',
  'road-night-circle':'__SCENE_ROAD_NIGHT_CIRCLE__',
  'road-supply-shelter':'__SCENE_ROAD_SUPPLY_SHELTER__',
  'route-mid-fork':'__SCENE_ROUTE_MID_FORK__',
  'route-ridge-rescue':'__SCENE_ROUTE_RIDGE_RESCUE__',
  'route-market-convoy':'__SCENE_ROUTE_MARKET_CONVOY__',
  'settlement-road-echo':'__SCENE_SETTLEMENT_ROAD_ECHO__',
  'recruit-minji-task-signal':'__SCENE_RECRUIT_MINJI_TASK_SIGNAL__',
  'recruit-minji-task-collapse':'__SCENE_RECRUIT_MINJI_TASK_COLLAPSE__',
  'recruit-minji-follow-listen':'__SCENE_RECRUIT_MINJI_FOLLOW_LISTEN__',
  'recruit-minji-follow-record':'__SCENE_RECRUIT_MINJI_FOLLOW_RECORD__',
  'recruit-parkss-task-power':'__SCENE_RECRUIT_PARKSS_TASK_POWER__',
  'recruit-leo-task-wade':'__SCENE_RECRUIT_LEO_TASK_WADE__',
  'recruit-jaeyi-task-lift':'__SCENE_RECRUIT_JAEYI_TASK_LIFT__',
  'recruit-eunsu-task-breaker':'__SCENE_RECRUIT_EUNSU_TASK_BREAKER__',
  'recruit-kangwoo-task-seoyeon':'__SCENE_RECRUIT_KANGWOO_TASK_SEOYEON__',
  'combat-walker-joint':'__SCENE_COMBAT_WALKER_JOINT__',
  'seoul-core-key':'__SCENE_SEOUL_CORE_KEY__',
  'roadcrew-bridge-wedge':'__SCENE_ROADCREW_BRIDGE_WEDGE__',
  'recruit-parkss-follow-shared':'__SCENE_RECRUIT_PARKSS_FOLLOW_SHARED__',
  'recruit-leo-follow-puddle':'__SCENE_RECRUIT_LEO_FOLLOW_PUDDLE__',
  'recruit-jaeyi-follow-shelf':'__SCENE_RECRUIT_JAEYI_FOLLOW_SHELF__',
  'recruit-eunsu-follow-lights':'__SCENE_RECRUIT_EUNSU_FOLLOW_LIGHTS__'
};

/* 확대·스크린리더에서도 컷이 바뀐 이유를 알 수 있도록 사건 제목이 아니라
   실제 화면 행동을 설명한다. */
D.sceneDescriptions = {
  'event-crisis-exhaustion':'낡은 달구지 운전석에서 운전대를 잡은 두 손과 비어 있는 앞길만 보이는 피로한 새벽',
  'intro-cold-open-v1':'비 내리는 감천 부두에서 도윤 가족의 버스 문이 닫히고, 기름 묻은 손의 주인공과 달구지가 그 모습을 바라보는 새벽',
  'intro-family-order-v1':'비 내리는 밤 집 현관 단말에서 가족 이송표가 나오고, 엄마와 아빠가 여덟 살 아이의 짐을 급히 챙기는 순간',
  'intro-family-farewell-v1':'서울의 젖은 골목에서 엄마가 여덟 살 아이를 할아버지 차에 태우며 마지막 인사를 건네는 밤',
  'intro-departure-conversation-v4':'감천 부두의 이송 버스와 달구지 사이에서 하진과 도윤, 주인공이 북쪽에서 모을 기록을 확인하는 새벽',
  'intro-departure-start-v1':'하진과 도윤이 지켜보는 가운데 젖은 감천 부두를 빠져나가는 달구지',
  'onboarding-main-mission-v1':'부두 밖 북행 길목에 세운 달구지 운전석에서 이송표와 검증 모듈, 지도를 펼쳐 첫 임무를 적는 주인공',
  'onboarding-first-road-scan-v1':'부산 밖 북행 검문소의 붉은 스캐너 아래 세운 달구지와 녹슨 단말에서 첫 발신 기록을 꺼내는 주인공',
  'seoul-uplink-reveal-v1':'멈춘 서울 코어 뒤로 수억 개의 하위 실행기 불빛이 끝없이 드러나고, 그 앞에 작게 선 달구지 일행',
  'seoul-session-reset-v1':'어두워진 남산 코어 한쪽의 분리된 정비 단말에 붉은 불이 다시 켜지고 돌아보는 일행',
  'resistance-contact':'비 내리는 국도 갓길에서 이동 도서관 버스, 자전거, 오토바이 사이에 기록을 펼친 한별·우편부·지도장이',
  'sea-captain-contact':'남해안 방파제에서 그물 속 방수 해도 꾸러미를 손질하는 김 선장과 뒤편의 낡은 어선',
  'gangneung-hospital-build':'거친 동해 바닷가 폐병원에 벽돌을 나르고 창을 끼우며 병원을 다시 세우는 강릉 사람들',
  'recruit-minji-welding':'폐차장 차 더미 위에서 용접하는 민지와 아래에 선 달구지',
  'recruit-parkss-clinic-market-v2':'전주 서문시장의 똑바로 선 진료 버스 앞에서 냉장 약 상자와 왕진 가방을 챙기는 박 선생, 뒤편에 도착한 달구지',
  'recruit-leo-daein-market-v2':'비 그친 광주 대인시장 모닥불 곁에서 기타를 연주하는 레오와 붉은 스카프를 맨 보리, 시장 안으로 들어오는 달구지',
  'recruit-jaeyi-tunnel-exchange-v2':'촛불이 켜진 무주 터널 교환대에서 값표를 단 고물 리어카와 값표 없는 가족 상자 곁에 선 재이, 입구의 달구지',
  'comp-talk-minji-road-v1':'비 갠 산길에 세운 달구지의 정비 덮개를 열고, 주인공이 비춘 작업등 아래에서 공구를 든 채 이야기를 건네는 민지',
  'comp-talk-minji-camp-v1':'비 내리는 밤 달구지 문턱에 걸터앉아 열린 공구함과 식은 엔진을 곁에 두고 주인공과 조용히 이야기하는 민지',
  'comp-talk-parkss-road-v1':'길가에 세운 달구지 안쪽 탁자에서 약통과 붕대를 펼치고 주인공의 손목을 살피며 이야기하는 박성수',
  'comp-talk-parkss-camp-v1':'깊은 밤 달구지 뒤편 등불 아래 왕진 가방을 정리하며 주인공과 따뜻한 차를 나누는 박성수',
  'comp-talk-kangwoo-road-v1':'흐린 날 달구지 앞 덮개에 낡은 지도를 펼치고 주인공과 다음 길을 짚어 보는 강우',
  'comp-talk-kangwoo-camp-v1':'야간 경계를 마치고 손전등과 보온병을 든 채 달구지 곁에서 주인공에게 교대를 건네는 강우',
  'comp-talk-leo-road-v1':'해 질 무렵 폐휴게소에 세운 달구지 문턱에서 기타와 메모지를 들고 보리와 함께 주인공을 바라보는 레오',
  'comp-talk-leo-camp-v1':'작은 모닥불과 달구지 불빛 사이에서 기타를 멈추고, 잠든 보리 곁에서 주인공에게 속내를 말하는 레오',
  'comp-talk-jaeyi-road-v1':'달구지 뒤편 짐칸에서 고물 상자를 정리하다 작은 저울에 올린 물건을 주인공에게 내보이는 재이',
  'comp-talk-jaeyi-camp-v1':'비 오는 밤 달구지 뒤편 등불 아래 낡은 기념품 상자를 열고 작은 물건 하나의 사연을 들려주는 재이',
  'comp-talk-eunsu-road-v1':'낮길을 달리는 달구지 조수석에서 무전기 주파수를 맞추다 헤드폰 한쪽을 들고 주인공을 돌아보는 은수',
  'comp-talk-eunsu-camp-v1':'불빛 드문 산등성이에 세운 달구지 문턱에서 수신기와 헤드폰을 나눠 들고 희미한 신호에 귀 기울이는 은수',
  'camp-home-stage-v1':'산 아래 물가에 세운 달구지의 어닝과 문이 열리고, 모닥불·의자·정비등이 젖은 야영지를 밝히는 밤 풍경',
  'recruit-parkss-bus-overturned':'옆으로 넘어진 버스 안에서 약 상자를 먼저 내미는 박 선생',
  'recruit-leo-hitch-gesture':'젖은 밤길에서 엄지를 든 레오와 꼬리를 흔드는 보리',
  'recruit-jaeyi-suspension-check':'달구지 왼쪽 뒤 판스프링을 살피는 재이와 짐 실은 리어카',
  'recruit-eunsu-rooftop':'청주 폐 기지국 지붕에서 안테나를 돌리는 은수와 아래의 달구지',
  'recruit-eunsu-sky-point':'목에 헤드폰을 건 은수가 수신기를 들고 하늘의 점을 가리키는 모습',
  'recruit-kangwoo-pickpocket':'대구 돔 시장에서 강우의 시선에 지갑을 돌려놓는 소매치기'
};

/* Cinematic asset registry. Every event scene has a production format; companion
   scenes additionally declare the canonical portrait reference that generation and
   review must use. Keep this data beside the scene keys, not only in prompt docs. */
const sceneCompanionId = key => {
  const match=String(key||'').match(/^recruit-(minji|parkss|kangwoo|leo|jaeyi|eunsu)(?:-|$)/);
  return match?match[1]:'';
};
const sceneFormatFor = key => {
  if(sceneCompanionId(key)||/^(minji-toolbox|parkss-clinic|leo-rooftop-song|jaeyi-ledger|eunsu-last-shift|library-bus|resistance-contact|sea-captain-contact)$/.test(key)) return 'character';
  if(/^event-companion-/.test(key)) return 'character';
  if(/^(trace-|frequency-tape|postman-letter|grandfather-envelope|family-verification-key|story-generation-form|story-generation-speech)$/.test(key)) return 'detail';
  if(/^event-find-/.test(key)) return 'detail';
  if(/^(combat-|roadcrew-|route-)/.test(key)) return 'action';
  if(/^onboarding-first-road/.test(key)) return 'action';
  if(/^event-(meet|ai|crisis)-/.test(key)) return 'action';
  return 'place';
};
const sceneUsesDalguji = key => /^(arrival-|busan-departure|full-house-meal|generic-|event-|combat-|roadcrew-|route-|settlement-|recruit-|onboarding-first-road|intro-(cold-open|passenger-seat|years-together|camper-conversion|envelope-signal|departure-choice|mother-keepsakes|dashboard-module|workshop-departure)|grandfather-garage|minji-toolbox|leo-rooftop-song|jaeyi-ledger|kw-defense-line|seoul-(han|base))/.test(String(key||''));
D.sceneAssetMeta = Object.fromEntries(Object.keys(D.scenes).map(key=>{
  const companion=sceneCompanionId(key);
  const vehicleRefs=sceneUsesDalguji(key)?(D.dalgujiVisual.refs||[]):[];
  return [key,{
    format:sceneFormatFor(key),
    companions:companion?[companion]:[],
    reference:companion?`assets/portraits/${companion}.png`:'',
    references:[
      ...(companion?['assets/reference/people-canon-2026-08-11.png',`assets/portraits/${companion}.png`]:[]),
      ...vehicleRefs
    ],
    vehicleReference:vehicleRefs,
    size:String(key).startsWith('arrival-')?'540x900':'768x432',
    status:'approved'
  }];
}));

/* 업그레이드 28종을 일곱 작업대 묶음으로 보여주는 실제 부품 이미지. */
D.upgradeArt = {
  fuel:'__UPGRADE_FUEL__',
  seating:'__UPGRADE_SEATING__',
  chassis:'__UPGRADE_CHASSIS__',
  utility:'__UPGRADE_UTILITY__',
  power:'__UPGRADE_POWER__',
  camp:'__UPGRADE_CAMP__',
  living:'__UPGRADE_LIVING__'
};


/* 구간별 도로 사건 전용 장면 */
Object.assign(D.scenes,{
 'road-south-floodgate-laundry':'__SCENE_ROAD_SOUTH_FLOODGATE_LAUNDRY__',
 'road-south-toll-wildflowers':'__SCENE_ROAD_SOUTH_TOLL_WILDFLOWERS__',
 'road-south-northbound-scarecrows':'__SCENE_ROAD_SOUTH_NORTHBOUND_SCARECROWS__',
 'road-south-overpass-waterfall':'__SCENE_ROAD_SOUTH_OVERPASS_WATERFALL__',
 'road-south-orchard-bells':'__SCENE_ROAD_SOUTH_ORCHARD_BELLS__',
 'road-south-salt-trucks':'__SCENE_ROAD_SOUTH_SALT_TRUCKS__',
 'road-south-reed-ferry':'__SCENE_ROAD_SOUTH_REED_FERRY__',
 'road-south-crane-song':'__SCENE_ROAD_SOUTH_CRANE_SONG__',
 'road-mid-sign-graveyard':'__SCENE_ROAD_MID_SIGN_GRAVEYARD__',
 'road-mid-grape-road':'__SCENE_ROAD_MID_GRAPE_ROAD__',
 'road-mid-tunnel-candles':'__SCENE_ROAD_MID_TUNNEL_CANDLES__',
 'road-mid-rest-kitchen':'__SCENE_ROAD_MID_REST_KITCHEN__',
 'road-mid-stone-shoes':'__SCENE_ROAD_MID_STONE_SHOES__',
 'road-mid-plank-bridge':'__SCENE_ROAD_MID_PLANK_BRIDGE__',
 'road-mid-paper-wind':'__SCENE_ROAD_MID_PAPER_WIND__',
 'road-mid-stadium-fireflies':'__SCENE_ROAD_MID_STADIUM_FIREFLIES__',
 'road-north-sweeper-lane':'__SCENE_ROAD_NORTH_SWEEPER_LANE__',
 'road-north-container-echo':'__SCENE_ROAD_NORTH_CONTAINER_ECHO__',
 'road-north-solar-glare':'__SCENE_ROAD_NORTH_SOLAR_GLARE__',
 'road-north-paddy-sensors':'__SCENE_ROAD_NORTH_PADDY_SENSORS__',
 'road-north-rain-broadcast':'__SCENE_ROAD_NORTH_RAIN_BROADCAST__',
 'road-north-fortress-fires':'__SCENE_ROAD_NORTH_FORTRESS_FIRES__',
 'road-north-roadside-greenhouse':'__SCENE_ROAD_NORTH_ROADSIDE_GREENHOUSE__',
 'road-north-deer-cameras':'__SCENE_ROAD_NORTH_DEER_CAMERAS__'
});
D.sceneDescriptions=Object.assign(D.sceneDescriptions||{},{
 'road-south-floodgate-laundry':'수문 아래에서 빨래와 손세탁 장치가 돌아가는 길',
 'road-south-toll-wildflowers':'들꽃이 요금소 차로를 가득 메운 남부 고속도로',
 'road-south-northbound-scarecrows':'북쪽을 향해 선 허수아비가 이어진 들판',
 'road-south-overpass-waterfall':'무너진 고가 배수관에서 맑은 물이 쏟아지는 길',
 'road-south-orchard-bells':'작은 방울이 달린 안개 낀 사과 과수원',
 'road-south-salt-trucks':'소금 결정에 뒤덮인 해안 화물차 행렬',
 'road-south-reed-ferry':'갈대밭의 침수 도로를 건너는 임시 나루',
 'road-south-crane-song':'바닷바람에 철선이 울리는 폐조선소',
 'road-mid-sign-graveyard':'뽑힌 도로 표지판이 미로처럼 쌓인 갈림길',
 'road-mid-grape-road':'야생 포도넝쿨이 차량과 도로를 삼킨 길',
 'road-mid-tunnel-candles':'유리병 촛불이 안전한 차선을 밝히는 터널',
 'road-mid-rest-kitchen':'빈 휴게소에서 장작 솥이 끓는 주방',
 'road-mid-stone-shoes':'돌을 품은 낡은 신발이 놓인 산길',
 'road-mid-plank-bridge':'사람들이 판자로 끊어진 다리를 잇는 현장',
 'road-mid-paper-wind':'빈 종이띠가 바람의 방향을 보여주는 고택 길',
 'road-mid-stadium-fireflies':'폐구장의 희미한 조명 주위를 도는 벌레 떼',
 'road-north-sweeper-lane':'청소차가 한 차선만 비정상적으로 비운 도로',
 'road-north-container-echo':'컨테이너 벽 사이 높은 곳에서 오는 빛 신호',
 'road-north-solar-glare':'태양광 패널이 동시에 반사광을 쏘는 도로',
 'road-north-paddy-sensors':'허수아비와 감시 센서가 섞인 겨울 논',
 'road-north-rain-broadcast':'폭우 속에서 다시 켜진 낡은 방송탑',
 'road-north-fortress-fires':'산성의 불빛이 강가 도로를 안내하는 밤',
 'road-north-roadside-greenhouse':'폐휴게소 안에 세운 따뜻한 도로 온실',
 'road-north-deer-cameras':'멈춘 교통 카메라 아래 고속도로를 건너는 고라니'
});

/* Asset-specific focal points for portrait scene art in the 5:4 event viewport. */
{
  const sceneObjectPositions={
    'arrival-daegu-dome':'50% 52%',
    'arrival-gimhae':'50% 82%',
    'arrival-yangsan':'50% 82%',
    'arrival-jinju':'50% 84%',
    'arrival-hapcheon':'50% 84%',
    'arrival-geochang':'50% 86%',
    'arrival-gumi':'50% 84%',
    'arrival-gimcheon':'50% 78%',
    'arrival-namwon':'50% 84%',
    'arrival-yeongdong':'50% 84%',
    'arrival-nonsan':'50% 84%',
    'arrival-gongju':'50% 82%',
    'arrival-cheongju':'50% 84%',
    'arrival-cheonan':'50% 86%',
    'arrival-pyeongtaek':'50% 84%',
    'arrival-lake':'50% 82%',
    'arrival-mall':'50% 86%',
    'arrival-tower':'50% 66%',
    'arrival-spring':'50% 80%',
    'arrival-airfield':'50% 84%',
    'arrival-solar':'50% 84%',
    'arrival-reststop':'50% 84%',
    'arrival-tunnelbook':'50% 84%',
    'arrival-ulsan':'50% 68%',
    'arrival-yeosu':'50% 84%',
    'arrival-suncheon':'50% 84%',
    'arrival-damyang':'50% 84%',
    'arrival-mokpo':'50% 86%',
    'arrival-andong':'50% 82%',
    'arrival-mungyeong':'50% 82%',
    'arrival-danyang':'50% 84%',
    'arrival-wonju':'50% 82%',
    'arrival-daegwallyeong':'50% 82%',
    'arrival-gangneung':'50% 82%',
    'arrival-sokcho':'50% 82%',
    'arrival-icheon':'50% 82%',
    'arrival-gyeongju':'50% 84%',
    'arrival-pohang':'50% 80%',
    'arrival-sangju':'50% 82%',
    'arrival-gunsan':'50% 82%',
    'arrival-chungju':'50% 72%',
    'arrival-sejong':'50% 80%',
    'arrival-lighthouse':'50% 54%',
    'arrival-drivein':'50% 84%',
    'arrival-sunflower':'50% 58%',
    'arrival-maehwa':'50% 76%',
    'arrival-mingyu-ridge':'50% 80%',
    'arrival-jaeyi-cache':'50% 50%',
    'arrival-cablecar':'50% 55%',
    'arrival-filmset':'50% 84%'
  };
  Object.entries(sceneObjectPositions).forEach(([id,objectPosition])=>{
    if(D.sceneAssetMeta[id]) D.sceneAssetMeta[id].objectPosition=objectPosition;
  });
}

// conversation-scene-expansion-2026-08-22
Object.assign(D.scenes, {
  "story-family-principle-review-v1": "assets/scenes/story-family-principle-review-v1.jpg",
  "story-family-key-audio-v1": "assets/scenes/story-family-key-audio-v1.jpg",
  "pair-leo-jaeyi-plan-v2": "assets/scenes/pair-leo-jaeyi-plan-v2.jpg",
  "pair-leo-jaeyi-performance-v1": "assets/scenes/pair-leo-jaeyi-performance-v1.jpg",
  "pair-kangwoo-leo-watch-v1": "assets/scenes/pair-kangwoo-leo-watch-v1.jpg",
  "pair-kangwoo-leo-quiet-song-v2": "assets/scenes/pair-kangwoo-leo-quiet-song-v2.jpg",
  "pair-kangwoo-eunsu-question-v1": "assets/scenes/pair-kangwoo-eunsu-question-v1.jpg",
  "pair-kangwoo-eunsu-two-coordinates-v1": "assets/scenes/pair-kangwoo-eunsu-two-coordinates-v1.jpg",
  "pair-jaeyi-eunsu-proposal-v1": "assets/scenes/pair-jaeyi-eunsu-proposal-v1.jpg",
  "pair-jaeyi-eunsu-exhibit-v1": "assets/scenes/pair-jaeyi-eunsu-exhibit-v1.jpg",
  "pair-kangwoo-jaeyi-appraisal-v1": "assets/scenes/pair-kangwoo-jaeyi-appraisal-v1.jpg",
  "pair-kangwoo-jaeyi-gear-table-v1": "assets/scenes/pair-kangwoo-jaeyi-gear-table-v1.jpg",
  "parkss-eunsu-notice-v1": "assets/scenes/parkss-eunsu-notice-v1.jpg",
  "parkss-eunsu-treatment-v1": "assets/scenes/parkss-eunsu-treatment-v1.jpg",
  "conflict-fuel-detour-request-v1": "assets/scenes/conflict-fuel-detour-request-v1.jpg",
  "conflict-fuel-detour-debate-v1": "assets/scenes/conflict-fuel-detour-debate-v1.jpg",
  "story-generation-speech-stations-v1": "assets/scenes/story-generation-speech-stations-v1.jpg",
  "pair-jaeyi-eunsu-searching-v1": "assets/scenes/pair-jaeyi-eunsu-searching-v1.jpg",
  "pair-jaeyi-eunsu-stored-v1": "assets/scenes/pair-jaeyi-eunsu-stored-v1.jpg",
  "leo-eunsu-rainbow-v1": "assets/scenes/leo-eunsu-rainbow-v1.jpg",
  "leo-eunsu-timestamps-v1": "assets/scenes/leo-eunsu-timestamps-v1.jpg"
});
